### ISSUE TITLE
Feature Request: add API

### ISSUE THREAD

**Issue by creeperita09** [TrinTragula/seeder#14]
hi, i would ask if it where possible to add an api so i can use this site in a discord bot without usinc pupeteer

**Comment by TrinTragula** [comment]
Hi! Since everything is done client side and hosting the map generation on my servers would really cost too much, I will probably never implement this feature, I'm sorry. 
Seed finding is an expensive task, that's why all the work on the website is done by the pc of the person connecting to it.
If you still want to implement your bot you can always use one of the libraries for seed generation floating around!
